import {createReportPdf} from '@/lib/report-pdf';
import {env} from 'cloudflare:workers';
import {z} from 'zod';
import {calculate,report} from '@/lib/calculator';
import {leadDb} from '@/lib/lead-db';
const schema=z.object({name:z.string().trim().min(2).max(120),email:z.string().email().max(160),agency:z.string().trim().min(2).max(160),city:z.string().trim().min(2).max(120),brand:z.string().max(100).default(''),phone:z.string().max(20).optional(),preference:z.enum(['email','call','session']),date:z.string().optional(),time:z.string().optional(),answers:z.array(z.number().int()).length(4),consent:z.literal(true),website:z.string().max(0).optional()});
export async function POST(request:Request){
 if(request.headers.get('origin')&&new URL(request.headers.get('origin')!).origin!==new URL(request.url).origin)return Response.json({error:'Solicitud no válida.'},{status:403});
 if(Number(request.headers.get('content-length')||0)>12000)return Response.json({error:'Solicitud demasiado grande.'},{status:413});
 let p:z.infer<typeof schema>;let result:ReturnType<typeof calculate>;
 try{const raw=await request.text();if(raw.length>12000)throw Error();p=schema.parse(JSON.parse(raw));result=calculate(p.answers);if(p.preference!=='email'&&(!p.phone||!/^\+?[0-9 ()-]{10,20}$/.test(p.phone)))throw Error();if(p.preference==='session'&&(!p.date||!/^\d{4}-\d{2}-\d{2}$/.test(p.date)||p.date<new Date().toLocaleDateString('en-CA',{timeZone:'America/Mexico_City'})||!p.time||!/^([01]\d|2[0-3]):[0-5]\d$/.test(p.time)))throw Error();}catch{return Response.json({error:'Revisa tus datos, las cuatro respuestas y el consentimiento.'},{status:400});}
 try{
 const db=leadDb();const now=Date.now();const recent=await db.prepare('SELECT COUNT(*) AS n FROM conversion_leads WHERE email = ? AND created_at > ?').bind(p.email,now-3600000).first<{n:number}>();if((recent?.n??0)>=3)return Response.json({error:'Ya recibimos tus solicitudes. Intenta más tarde.'},{status:429});
 const id=crypto.randomUUID();await db.prepare('INSERT INTO conversion_leads (id,name,email,agency,city,brand,phone,preference,preferred_date,preferred_time,answers,result,consent_version,email_status,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,p.name,p.email,p.agency,p.city,p.brand,p.preference==='email'?null:p.phone!,p.preference,p.preference==='session'?p.date!:null,p.preference==='session'?p.time!:null,JSON.stringify(p.answers),JSON.stringify(result),'2026-09-27: resumen + seguimiento solo si solicitado','pending',now).run();
 const cfg=env as unknown as {RESEND_API_KEY?:string;EMAIL_FROM?:string};let sent=false;
 if(cfg.RESEND_API_KEY&&cfg.EMAIL_FROM){try{const pdf=await createReportPdf(p.answers);let binary='';for(const byte of pdf)binary+=String.fromCharCode(byte);const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${cfg.RESEND_API_KEY}`,'Content-Type':'application/json','Idempotency-Key':id},body:JSON.stringify({from:cfg.EMAIL_FROM,to:[p.email],subject:'Tu ejercicio de conversión | Coldwell Banker',attachments:[{filename:'Mi-ejercicio-Coldwell-Banker.pdf',content:btoa(binary)}],text:`Hola, ${p.name}.\n\n${report(p.answers)}\nPreferencia de seguimiento: ${p.preference==='email'?'Solo el ejercicio solicitado. No te llamaremos ni te contactaremos por WhatsApp o correo para seguimiento. Cuando estés listo, vuelve al sitio o llama al 55 4162 1060':p.preference==='call'?'Llamada de diagnóstico':'Solicitud de sesión el '+p.date+' a las '+p.time+' (CDMX), pendiente de confirmación'}.`})});sent=response.ok;if(sent)await db.prepare('UPDATE conversion_leads SET email_status = ? WHERE id = ?').bind('sent',id).run();}catch{/* Keep the pending request for review; never claim an email was sent. */}}
 return Response.json({id,message:sent?`Tu ejercicio fue enviado a ${p.email}. ${p.preference==='email'?'No te llamaremos ni enviaremos mensajes de seguimiento. Cuando estés listo, puedes volver al sitio o llamar al 55 4162 1060.':'Tu solicitud de asesoría quedó registrada; la sesión requiere confirmación.'}`:'Tu solicitud quedó registrada. El envío por correo está pendiente de habilitación. Mientras tanto, puedes guardar tu ejercicio con el botón «Guardar ejercicio».'},{status:201});
 }catch(error){console.error('Lead registration failed',error instanceof Error?error.message:'unknown');return Response.json({error:'No pudimos guardar tu solicitud. Conservamos tus respuestas en pantalla; vuelve a intentarlo.'},{status:503});}
}
